package com.turlygazhy.entity;

/**
 * Created by user on 1/17/17.
 */
public enum WaitingType {
    CONTACT,
    COMMAND,
    PHONE_NUMBER,
    NAME,
    CITY,
    SEX,
    BIRTHDAY,
    HAVE_CAR, ACCEPT, DESCRIPTION, DATE, MESSAGE, TYPE_OF_WORK, STOCK_COMMAND, CHOOSE, TITLE, TEXT, PHOTO, EDIT_NEWS, EDIT_NEWS_TITLE, EDIT_NEWS_TEXT, EDIT_NEWS_PHOTO, SHOW_USER, FOR_WHOM, CHOOSE_TYPE_OF_WORK, CHOOSE_TASK, SURVEY_NAME, QUESTION, QUESTION_BUTTON, END, ANSWER,


}
